# **1. 파이토치**
PyTorch는 파이썬 기반의 오픈소스 딥러닝 프레임워크로, 파이썬 코드로 AI 모델을 직관적으로 만들고 학습할 수 있도록 도와주는 도구입니다.  
특히 동적 계산 그래프 방식을 사용하기 때문에 코드 실행 시점에 실시간으로 계산 흐름이 결정되어 디버깅과 수정이 쉽고, GPU 가속과 자동 미분 기능을 통해 대규모 모델도 빠르게 학습할 수 있습니다.

### ※ 동적 계산 그래프 방식

딥러닝 모델이 학습 및 예측을 수행할 때 계산 그래프를 실행 시점(runtime)에 실시간으로 생성 및 수정하는 방식입니다.  
이 방식은 조건문, 반복문 등 복잡한 논리 구조를 유연하게 처리할 수 있으며, 주로 PyTorch와 같은 프레임워크에서 사용됩니다.  
계산 그래프는 입력 데이터를 바탕으로 연산을 수행하면서 그래프를 생성하고, 역전파를 통해 미분을 계산하며, 최종적으로 가중치를 업데이트하는 과정을 거칩니다.  
이러한 특성 덕분에 디버깅이 용이하고 연구 및 개발 속도가 빠르며 직관적인 코드 작성이 가능합니다.

In [1]:
import torch

In [2]:
if torch.cuda.is_available():
    DEVICE = torch.device('cuda')
elif torch.backends.mps.is_available():
    DEVICE = torch.device('mps')
elif torch.xpu.is_available():
    DEVICE = torch.device('xpu')
else:
    DEVICE = torch.device('cpu')

print(DEVICE)

cpu


### 1. 스칼라

스칼라(Scalar)는 단 하나의 숫자(정수, 실수 등)만을 담는 자료형을 말합니다.  
파이토치(PyTorch)에서 스칼라는 0차원 텐서(0-dimensional Tensor)로 표현합니다.  
즉, 텐서의 차원(Shape)이 전혀 없는 상태를 의미합니다.

In [3]:
var1 = torch.tensor(5)
print(var1)
print(var1.shape)

var2 = torch.tensor([10])
print(var2.shape)
var2 = torch.tensor([10, 20, 30])
print(var2.shape)

var3 = torch.tensor(3)
result = var1 + var3
print(result)

result2 = var1 + var2
print(result2)

print(result.item())

tensor(5)
torch.Size([])
torch.Size([1])
torch.Size([3])
tensor(8)
tensor([15, 25, 35])
8


### 2. 벡터(Vector)

벡터(Vector)는 하나 이상의 원소가 일렬로 나열된 1차원 텐서(1D Tensor)를 의미합니다.  
파이토치(PyTorch)에서 벡터는 일반적으로 torch.tensor([...]) 형태로 만들며, 이때 텐서의 shape(차원)가 (n,) 형태입니다. 즉, 원소가 n개 들어 있으면 1차원 벡터가 됩니다.

In [4]:
var1 = torch.tensor([1.0, 2.0, 3.0])
print(var1)
var1 = torch.FloatTensor([1, 2, 3])
print(var1)
print(var1.shape)

var2 = var1 + 10
print(var2)

var3 = var1 * 2
print(var3)

var4 = torch.tensor([4.0, 5.0, 6.0])
result = var1 + var4
print(result)

tensor([1., 2., 3.])
tensor([1., 2., 3.])
torch.Size([3])
tensor([11., 12., 13.])
tensor([2., 4., 6.])
tensor([5., 7., 9.])


### 3. 행렬

행렬(Matrix)은 2차원 형태의 텐서로, 파이토치(PyTorch)에서는 shape가 (m, n)처럼 2개의 차원을 가진 텐서를 의미합니다.  
예를 들어, torch.tensor([[1, 2], [3, 4]])는 2행×2열 형태의 행렬입니다.  
행렬 연산에서는 행렬 곱셈, 원소별 연산, 전치(Transpose) 등이 자주 활용되며, 파이토치는 torch.mm 또는 @ 연산자를 통해 행렬 곱셈을 수행할 수 있습니다.

In [5]:
var1 = torch.tensor([[1, 2], [3, 4]])
var2 = torch.tensor([[5, 6], [7, 8]])
print(var1)
print(var1.shape)

result = var1 + var2
print(result)

result2 = var1 * var2
print(result2)

result3 = torch.mm(var1, var2)
print(result3)

result4 = var1 @ var2
print(result4)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


### 4. 다차원 텐서

파이토치(PyTorch)에서 다차원 텐서란, 여러 축(차원)을 가지는 텐서를 의미합니다.  
예를 들어, 0차원 텐서는 “스칼라(Scalar)”, 1차원 텐서는 “벡터(Vector)”, 2차원 텐서는 “행렬(Matrix)”,  
그 이상의 3차원, 4차원 텐서 등을 통틀어 “다차원 텐서(Multi-dimensional Tensor)”라고 부릅니다.  
다차원 텐서는 이미지, 음성, 동영상, 시계열 데이터를 비롯하여 여러 축을 필요로 하는 다양한 형태의 데이터를 표현할 때 쓰입니다.

![다차원텐서](./images/다차원텐서.png)

In [6]:
var1 = torch.tensor([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

print(var1)
print(var1.shape)  # torch.Size([2, 2, 2])

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


# **2. 텐서**
PyTorch의 텐서(Tensor)는 딥러닝 모델에서 데이터를 다룰 때 사용되는 기본 데이터 구조입니다.  
텐서는 다차원 배열로, NumPy의 배열과 비슷하지만, GPU에서 연산을 수행할 수 있다는 점에서 차이가 있습니다.  
PyTorch의 텐서는 데이터의 표현뿐만 아니라, 자동 미분(autograd) 기능을 제공하여 딥러닝 모델의 학습을 도와줍니다.

In [7]:
data = [
    [1, 2],
    [3, 4]
]

t1 = torch.tensor(data)
print(t1)

tensor([[1, 2],
        [3, 4]])


In [10]:
t1 = torch.tensor([5])
t2 = torch.tensor([7])

ndarr1 = (t1 + t2).numpy()
print(ndarr1)
print(type(ndarr1))

result = ndarr1 * 10
t3 = torch.from_numpy(result)
print(t3)
print(type(t3))

[12]
<class 'numpy.ndarray'>
tensor([120])
<class 'torch.Tensor'>


In [16]:
t1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(t1[0])
print(t1[:, 0])
print(t1[:, -1])
print(t1[..., -1])

tensor([1, 2, 3, 4])
tensor([1, 5, 9])
tensor([ 4,  8, 12])
tensor([ 4,  8, 12])


In [18]:
t1 = torch.tensor([[[1, 2, 3],
                    [4, 5, 6]],
                    [[7, 8, 9],
                    [10, 11, 12]]])

print(t1.shape)
print(t1[..., -1])

torch.Size([2, 2, 3])
tensor([[ 3,  6],
        [ 9, 12]])


# **3. GPU 사용**
GPU (Graphics Processing Unit)는 그래픽 처리 장치로, 주로 이미지 렌더링과 같은 대규모 병렬 계산을 수행하는 데 최적화된 하드웨어입니다.  
원래는 그래픽 처리를 위해 설계되었지만, 최근에는 인공지능(AI) 및 딥러닝의 연산 가속기로 널리 사용되고 있습니다.  
딥러닝은 수천, 수만 개의 행렬 및 벡터 연산을 필요로 합니다. GPU는 여러 개의 코어를 사용하여 이 연산을 병렬로 처리할 수 있습니다.  
따라서 GPU는 딥러닝 에 최적화된 구조를 가지고 있습니다.

In [ ]:
data = [
    [1, 2],
    [3, 4]
]

t1 = torch.tensor(data)
print(t1.is_cuda)

t1 = t1.cuda() # GPU로 옮기기
print(t1.is_cuda)

t1 = t1.cpu() # CPU로 옮기기
print(t1.is_cuda)

In [25]:
t1 = torch.tensor([
    [1, 1],
    [2, 2]
]).cuda()

t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

# print(torch.matmul(t1, t2))
print(torch.matmul(t1.cpu(), t2))
print(f"Device: {t1.device}")

AssertionError: Torch not compiled with CUDA enabled

# **4. 텐서의 연산과 함수**

In [26]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])

t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)

tensor([[ 6,  8],
        [10, 12]])
tensor([[-4, -4],
        [-4, -4]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [27]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])
t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

print(t1.matmul(t2))
print(torch.matmul(t1, t2))

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [31]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(t1)
print(t1.mean())       # 전체 원소에 대한 평균
print(t1.mean(dim=0))  # 각 열에 대하여 평균 계산
print(t1.mean(dim=1))  # 각 행에 대하여 평균 계산

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(4.5000)
tensor([3., 4., 5., 6.])
tensor([2.5000, 6.5000])


In [32]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(t1)
print(t1.sum())      # 전체 원소에 대한 합계
print(t1.sum(dim=0)) # 각 열에 대하여 합계 계산
print(t1.sum(dim=1)) # 각 행에 대하여 합계 계산

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(36.)
tensor([ 6.,  8., 10., 12.])
tensor([10., 26.])


In [34]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(t1)
print(t1.argmax())      # 전체 원소에 대한 최댓값의 인덱스
print(t1.argmax(dim=0)) # 각 열에 대하여 최댓값의 인덱스 계산
print(t1.argmax(dim=1)) # 각 행에 대하여 최댓값의 인덱스 계산

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(7)
tensor([1, 1, 1, 1])
tensor([3, 3])


# **5. 텐서의 차원 조작**

In [37]:
t1 = torch.tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# dim: 텐서를 이어 붙이기 위한 축
# 0번 축(행)을 기준으로 이어 붙이기
result = torch.cat([t1, t1, t1], dim=0)
print(result)

# 1번 축(열)을 기준으로 이어 붙이기
result = torch.cat([t1, t1, t1], dim=1)
print(result)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  1,  2,  3,  4,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  5,  6,  7,  8,  5,  6,  7,  8],
        [ 9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12]])


In [38]:
t1 = torch.tensor([2], dtype=torch.int)
t2 = torch.tensor([5.0])

print(t1.dtype)
print(t2.dtype)

# 텐서 t1는 자동으로 float32형으로 형변환 처리
print(t1 + t2)
# 텐서 t2를 int32형으로 형변환하여 덧셈 수행
print(t1 + t2.type(torch.int32))

torch.int32
torch.float32
tensor([7.])
tensor([7], dtype=torch.int32)


In [41]:
# view()는 텐서의 모양을 변경할 때 사용한다.
# 이때, 텐서(tensor)의 순서는 변경되지 않는다.
t1 = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8])
t2 = t1.view(4, 2)
print(t2)

# t1의 값을 변경하면 t2도 변경
t1[0] = 7
print(t1)
print(t2)

# t1의 값을 복사(copy)한 뒤에 변경
t3 = t1.clone().view(4, 2)
t1[0] = 9
print(t1)
print(t3)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([7, 2, 3, 4, 5, 6, 7, 8])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([9, 2, 3, 4, 5, 6, 7, 8])
tensor([[7, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [42]:
t1 = torch.rand((64, 32, 3))
print(t1.shape)

# permute(): 차원 자체를 교환
t2 = t1.permute(2, 1, 0) # 차원 자체를 교환: (3, 32, 64)
# (2번째 축, 1번째 축, 0번째 축)의 형태가 됨
print(t2.shape)

torch.Size([64, 32, 3])
torch.Size([3, 32, 64])


In [43]:
t1 = torch.Tensor([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(t1.shape)

# 첫 번째 축에 차원 추가
t1 = t1.unsqueeze(0)
print(t1)
print(t1.shape)

# 네 번째 축에 차원 추가
t1 = t1.unsqueeze(3)
print(t1)
print(t1.shape)

torch.Size([2, 4])
tensor([[[1., 2., 3., 4.],
         [5., 6., 7., 8.]]])
torch.Size([1, 2, 4])
tensor([[[[1.],
          [2.],
          [3.],
          [4.]],

         [[5.],
          [6.],
          [7.],
          [8.]]]])
torch.Size([1, 2, 4, 1])


In [48]:
# 크기가 1인 차원 제거, squeeze(dim): 특정 차원이 1인 경우에만 차원을 제거
# t1 = t1.squeeze() # 크기가 1인 차원을 모두 제거
t1 = t1.squeeze()
print(t1)
print(t1.shape)
t1 = t1.squeeze(0)  # 크기가 1인 차원 중 0번 차원을 제거
print(t1.shape)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4])
torch.Size([2, 4])


# **6. 자동 미분과 기울기**
### 1. 미분
미분(Differentiation)​이란 어떤 값이 얼마나 빠르게 변하는지를 계산하는 수학적인 방법입니다.  
쉽게 말해, 입력값(x)이 아주 조금 변했을 때 출력값(y)이 얼마나 변하는지​를 나타내는 기울기(변화율)​를 구하는 것입니다.  
딥러닝에서는 이 기울기를 이용해 모델의 가중치가 결과에 얼마나 영향을 주는지 계산하고, 이를 바탕으로 가중치를 조금씩 수정하여 모델의 성능을 향상시킵니다.

```
자동미분을 이해하기 위해 가장 간단한 함수인 y = x²를 살펴보겠습니다.

예를 들어 x = 3이라면,
y = 3² = 9

이 함수를 미분하면 아래와 같습니다.
y를 x에 대해 미분하면 2x
dy/dx = 2x 

여기에 x = 3을 대입하면,
dy/dx = 2 × 3 = 6

x가 아주 조금 변할 때 y가 얼마나 변하는지를 나타내는 비율(기울기)
즉, x = 3인 지점에서 함수의 기울기(미분값)는 6이라는 의미입니다.
```

In [52]:
# 미분할 변수 x 생성
# 이 값이 이후 계산 결과에 얼마나 영향을 주는지 미분할 예정
x = torch.tensor(3.0, requires_grad=True)

# 함수 y = x²
y = x ** 2

# y를 기준으로 x에 대한 미분값 계산
# y에서 출발하여 계산 그래프를 거꾸로 이동하면서 미분합니다.
# 정방향 계산: x = 3 > y = x² > y = 9
# 역방향 계산: y > dy/dx = 2x > x = 3이므로 6
y.backward()

print("x 값:", x)
print("y 값:", y)
# 현재 x=3 근처에서 x가 조금 변할 때 y가 얼마나 민감하게 변하는지를 나타냅니다.
print("x의 미분값:", x.grad)

x 값: tensor(3., requires_grad=True)
y 값: tensor(9., grad_fn=<PowBackward0>)
x의 미분값: tensor(6.)
